"""Aggregate every run under `runs/` into one results table, then render the
Hugging Face model card from it.

The point of generating cards from `results.json` rather than writing them by
hand is that the card cannot drift from the run that produced it. If a number
appears on the Hub, there is a config and an environment dump behind it.

    python -m prefopt.report --runs runs --out RESULTS.md
    python -m prefopt.report --runs runs --card cards/model_card_policy.md.j2 \
        --card-run runs/dpo_b0.1 --card-out runs/dpo_b0.1/README.md
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from .utils import get_logger, load_json

logger = get_logger(__name__)

COLUMNS = [
    ("run", "Run"),
    ("stage", "Stage"),
    ("beta", "beta"),
    ("num_generations", "G"),
    ("rm_pair_fraction", "RM data"),
    ("rm_accuracy", "RM acc"),
    ("win_rate", "Win-rate vs SFT"),
    ("ci", "95% CI"),
    ("swap_consistency", "Swap cons."),
    ("length_reward_corr", "len/reward rho"),
    ("kl", "KL from ref"),
]


def collect(runs_dir: Path) -> list[dict[str, Any]]:
    rows = []
    for run_dir in sorted(p for p in runs_dir.iterdir() if p.is_dir()):
        cfg_path = run_dir / "config.resolved.yaml"
        if not cfg_path.exists():
            continue
        cfg = yaml.safe_load(cfg_path.read_text()) or {}
        row: dict[str, Any] = {
            "run": run_dir.name,
            "stage": cfg.get("stage", ""),
            "beta": cfg.get("method", {}).get("beta"),
            "num_generations": cfg.get("method", {}).get("num_generations"),
            "rm_pair_fraction": cfg.get("data", {}).get("rm_pair_fraction"),
        }

        rm_eval = run_dir / "rm_eval.json"
        if rm_eval.exists():
            row["rm_accuracy"] = load_json(rm_eval).get("eval_accuracy")

        results = run_dir / "results.json"
        if results.exists():
            res = load_json(results)
            row["win_rate"] = res.get("win_rate_mean")
            per_seed = res.get("per_seed") or []
            if per_seed:
                lo = min(s["ci95"][0] for s in per_seed)
                hi = max(s["ci95"][1] for s in per_seed)
                row["ci"] = f"[{lo:.3f}, {hi:.3f}]"
                row["swap_consistency"] = sum(
                    s["swap_consistency"] for s in per_seed
                ) / len(per_seed)

        diag = run_dir / "diagnostics.json"
        if diag.exists():
            d = load_json(diag)
            row["length_reward_corr"] = d.get("length_reward_corr")
            row["kl"] = d.get("kl_from_reference")

        rows.append(row)
    return rows


def _fmt(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def to_markdown(rows: list[dict[str, Any]]) -> str:
    header = "| " + " | ".join(label for _, label in COLUMNS) + " |"
    rule = "|" + "|".join("---" for _ in COLUMNS) + "|"
    lines = [header, rule]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(row.get(key)) for key, _ in COLUMNS) + " |")
    return "\n".join(lines)


def render_card(template_path: Path, run_dir: Path, out_path: Path) -> None:
    from jinja2 import Template

    cfg = yaml.safe_load((run_dir / "config.resolved.yaml").read_text())
    context: dict[str, Any] = {"cfg": cfg, "run": run_dir.name}
    for name, filename in (
        ("results", "results.json"),
        ("diagnostics", "diagnostics.json"),
        ("environment", "environment.json"),
        ("rm_eval", "rm_eval.json"),
    ):
        path = run_dir / filename
        context[name] = load_json(path) if path.exists() else None

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(Template(template_path.read_text()).render(**context))
    logger.info("Card written to %s", out_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate results and render cards")
    parser.add_argument("--runs", default="runs")
    parser.add_argument("--out", default="RESULTS.md")
    parser.add_argument("--card", default=None, help="Jinja template for a HF card.")
    parser.add_argument("--card-run", default=None)
    parser.add_argument("--card-out", default=None)
    args = parser.parse_args()

    rows = collect(Path(args.runs))
    if not rows:
        logger.warning("No runs with config.resolved.yaml found under %s", args.runs)
    table = to_markdown(rows)
    Path(args.out).write_text(
        "# Results\n\nGenerated by `python -m prefopt.report`. "
        "Every row is backed by a `config.resolved.yaml` and an "
        "`environment.json` in the corresponding run directory.\n\n" + table + "\n"
    )
    logger.info("Wrote %s (%d runs)", args.out, len(rows))
    print(table)

    if args.card:
        if not (args.card_run and args.card_out):
            parser.error("--card requires --card-run and --card-out")
        render_card(Path(args.card), Path(args.card_run), Path(args.card_out))


if __name__ == "__main__":
    main()
